[package]
name = "pinetime-rust-firmware"
version = "0.1.0"
edition = "2021"
authors = ["beattie"]

[dependencies]
cortex-m = "0.7"
cortex-m-rt = "0.7"
embedded-hal = "0.2"
nrf52832-hal = "0.15"
panic-halt = "0.2"
